# -*- coding: utf-8 -*-
"""FinanceApp

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pjXXv1NNHtlbdqjQsp8bf0DHO0XGAJhy
"""

!pip install streamlit pandas plotly numpy
import streamlit as st
import pandas as pd
import plotly.express as px
import json
import os

st.set_page_config(page_title="Finance App", page_icon="💸", layout="wide")

def load_transactions(file):
  pass

def main():
    st.title("Finance Dashboard")

    uploaded_file= st.file_uploader("Upload CSV bank statement", type=["csv"])
    if uploaded_file is not None:
      df = load_transactions(uploaded_file)